FROM node:14-alpine AS builder

WORKDIR /app

COPY . .

RUN npm install

RUN npm build

RUN npm prune --production

FROM node:14-alpine AS production

WORKDIR "/app"


COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/package-lock.json ./package-lock.json
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

ENV CORS_HOSTNAME="http://localhost:8100"
ENV MONGODB_CONNECTIONSTRING="mongodb://localhost/orgexplorr-dev"
ENV JWT_EXPIRESIN="123456"
ENV JWT_SECRET="repalcethisbadsecretkey"
ENV NODE_PORT=80
EXPOSE 80
CMD [ "sh", "-c", "npm run start:prod"]